package br.com.leiras.euler;

/**
* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
* 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
* 
* By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
* 
* @author leiras 
*/
public class Problem2 {

	public static void main(String[] args) {
		int maxValue = 4000000;
		int sum = 0;
		int previous = 0;
		int current = 1;
		int next = previous + current;
		while (next <= maxValue) {
			if (next%2 == 0) {
				sum += next;				
			}
			System.out.println(next);
			previous = current;
			current = next;
			next = previous + current;	
		}
		System.out.println("Result: "+sum);
	}

}
